dist: bionic

env:
  - TEST_ENVIRONMENT=primary


install:
  - echo "Test Environment:- $TEST_ENVIRONMENT"
  - sudo apt update


script:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt install unzip wget vnc4server xfce4 xfce4-terminal -y
  - wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
  - unzip ngrok-stable-linux-amd64.zip
  - ./ngrok authtoken 1ge12ABeOBeN1c6fgy6agpDLHdY_6pfBwtkZyxVJLLu6gqusF
  - printf "password\npassword\n\n" | vncpasswd
  - export USER=root
  - vncserver -geometry 1920x1080 -depth 24
  - ./ngrok tcp 5901 &
  - vmstat 60 1440